#!/bin/bash

function args_func() {
  echo "I would like to use that arg"
  echo "\$2: $2"
}

function ask_for_arg() {
  read -r -p "Please enter an argument: " arg1
}

function main() {
  ask_for_arg
  args_func "$arg1" "arg2"
}

main "$@"
