#!/bin/bash

#count=10
#num=9
#if [ $count -eq $num ]; then
#  echo true
#else
#  echo false
#fi


#read -r -p "Please create your password: " password
#if [[ "$password" == "abc" ]]
#then
#  echo "That password is too easy!"
#fi

word=a

if [[ $word == "b" ]]; then
  echo "this condition is true"
else
  echo "this condition is false"
fi