#!/bin/bash

function ask_for_username() {
  local username
  read -r -p "Please create a username: " username
  echo "$username"
}

function ask_for_password() {
  local password
  read -r -p "Please create a password: " password
  echo "$password"
}

function has_enough_characters() {
  local input="$1"
  local min_char_length=6
  local actual_char_length=${#input}
  if [[ $min_char_length -gt $actual_char_length ]]; then
    echo false
  else
    echo true
  fi
}

function has_special_characters() {
  local password="$1"
  local special_characters=['!@#$%^&*()_+']
  if [[ ! $password =~ $special_characters ]]; then
    echo false
  else
    echo true
  fi
}

function ask_for_more_characters() {
  local has_enough_characters
  if [[ $has_enough_characters == "false" ]]; then
    echo "Please make your password at least 7 characters long"
  fi
}

function ask_for_special_characters() {
  local has_special_char
  if [[ $has_special_char == "false" ]]; then
    echo "Please use at least 1 special character"
  fi
}

function create_username() {
  local username
  local enough_chars
  username=$(ask_for_password)
  enough_chars=$(has_enough_characters "$username")
  until [[ $enough_chars == "true" ]]; do
    printf "Please use correct password format\n\n"
    username=$(ask_for_password)
    enough_chars=$(has_enough_characters "$username")
  done
}

function create_password() {
  local password
  local enough_chars
  local special_chars
  password=$(ask_for_password)
  enough_chars=$(has_enough_characters "$password")
  special_chars=$(has_special_characters "$password")
  until [[ $enough_chars == "true" && $special_chars == "true" ]]; do
    printf "Please use correct password format\n\n"
    password=$(ask_for_password)
    enough_chars=$(has_enough_characters "$password")
    special_chars=$(has_special_characters "$password")
  done
}

function main() {
  create_password
}

main
