#!/bin/bash

function ask_for_password() {
  read -r -p "Please create a password: " password
}

function has_enough_characters() {
  has_enough_chars=true
  local min_char_length=5
  local actual_char_length=${#password}
  if [[ $min_char_length -gt $actual_char_length ]]; then
    echo "Please have at least 5 characters for your password"
    has_enough_chars=false
  fi
}

function has_special_characters() {
  has_special_char=true
  local special_characters=['!@#$%^&*()_+']
  if [[ ! $password =~ $special_characters ]]; then
    echo "Please use a special character"
    has_special_char=false
  fi
}

function main() {
  password=$(ask_for_password)
  has_enough_characters
  until [ "$has_enough_chars" = "true" ]; do
    echo "has enough characters == $has_enough_chars"
    password=$(ask_for_password)
    has_enough_characters
    echo "Password is $password"
  done
}

main "$@"