#!/bin/bash

password="39g"

function no_special_character() {
  local special_characters=['!@#$%^&*()_+']
  if [[ $password =~ $special_characters ]]; then echo false; else echo true; fi
}

function not_enough_characters() {
    local min_char_length=5
    local actual_char_length=${#password}
    if [[ "$min_char_length" -gt "$actual_char_length" ]]; then echo false; else echo true; fi
}

not_enough_chars="$(not_enough_characters)"
echo "$not_enough_chars"

if [[ $not_enough_chars == "true" ]]; then
  echo "Password doesn't have enough characters"
elif [[ "${not_enough_char}" == "false" ]]; then
  echo "Password has enough characters! :)"
fi

str="yees"
if [[ $str == "yes" ]]; then
  echo "the answer is yes"
else
  echo "the answer is no"
fi
